---
- name: Playbook Powershell IIS log rotate
  hosts: all
  tasks:
    - name: Powershell IIS log rotate
      ansible.windows.win_powershell:
        script: |
          echo "Start Script"
          $LogPath = "C:\inetpub\logs"
          $maxDaystoKeep = -15
          $itemsToDelete = dir $LogPath -Recurse -File *.log | Where LastWriteTime -lt ((get-date).AddDays($maxDaystoKeep)) 
          if ($itemsToDelete.Count -gt 0){ 
            ForEach ($item in $itemsToDelete){ 
            Remove-Item $item.FullName -Verbose
           } 
          }
          Write-Output "Cleanup of log files older than $((get-date).AddDays($maxDaystoKeep)) completed..."
          start-sleep -Seconds 10
